project_name: http-echo
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
      - "-X github.com/verifa/http-echo/version.Version={{.Version}}"
      - "-X github.com/verifa/http-echo/version.Commit={{.Commit}}"
      - "-X github.com/verifa/http-echo/version.Date={{.Date}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc

brews:
  - name: http-echo
    tap:
      owner: verifa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/verifa/http-echo"
    description: "http-echo"
    test: |
      system "#{bin}/http-echo --version"

dockers:
  - goos: linux
    goarch: amd64
    skip_push: "false"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "verifa/{{ .ProjectName }}:latest"
      - "verifa/{{ .ProjectName }}:{{ .Tag }}"
      - "verifa/{{ .ProjectName }}:{{ .Major }}"
      - "verifa/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "verifa/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
      - "--pull"

release:
  github:
    owner: verifa
    name: http-echo
  prerelease: auto
  disable: false
  draft: false
