# This Dockerfile is written for use with goreleaser
FROM gcr.io/distroless/base-debian10

# Copy the static executable built by goreleaser
COPY http-echo /http-echo

# Run as unprivileged user
USER nonroot:nonroot

ENTRYPOINT ["/http-echo"]
